  name: cicd for releases
  
  on:
    push:
      tags:
        - 'release-v[0-9]+.[0-9]+.[0-9]+' # e.g. release-v1.3.22
  
  jobs:
    deploy_qa:
      name: Deploy to qa 
      runs-on: ubuntu-latest
      environment: 
        name: qa
        url: 'http://qa.test.domain'
      steps:
        - name: Deploy
          run: echo 'Deploying...to...qa $GITHUB_REF'

    deploy_staging:
      name: Deploy to staging 
      needs: [deploy_qa]
      runs-on: ubuntu-latest
      environment: 
        name: staging
        url: 'http://test.domain'
      steps:
        - name: Deploy
          run: echo Deploying...to...staging

    deploy_prod:
      name: Deploy to prod
      needs: [deploy_staging]
      runs-on: ubuntu-latest
      environment: 
        name: prod
        url: 'http://test.domain'
      steps:
        - name: Deploy
          run: echo Deploying...to...staging
