name: cicd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: echo Building...
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run Unit Tests
        run: echo Testing your units... :X
           
  deploy_dev:
    name: Deploy to dev 
    if: github.event_name == 'pull_request' || github.event.ref == 'refs/heads/main'
    needs: [build, test]
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: 'https://dev.test.domain'
    steps:
      - name: Deploy
        run: echo Deploying...to...dev
        
  create_release: # TODO add ECR push from build output
    name: Create GH Release
    if: github.event.ref == 'refs/heads/main'
    needs: [build, test, deploy_dev]
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://github.com/${{ github.repository }}/releases/tag/${{ steps.semantic-release.outputs.release-tag }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node Env
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.x
      - name: Release w/ Semantic-Release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
             npx semantic-release@18 \
             --plugins '@semantic-release/commit-analyzer',\
             '@semantic-release/release-notes-generator',\
             '@semantic-release/github', \
             '["@semantic-release/exec", {
               "publishCmd": "echo "release-tag=${nextRelease.version}\n" >> $GITHUB_OUTPUT"
             }]' \
             --tag-format 'release-v${version}' \
             --branches 'main'
