name: Deploy only

on:
  release:
    types: [published]

jobs:
  deploy_dev:
    name: Deploy to dev 
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: 'https://dev.test.domain'
    steps:
      - name: Deploy
        run: echo "Deploying...to...dev $GITHUB_REF"

  deploy_qa:
    name: Deploy to qa
    needs: [deploy_dev]
    runs-on: ubuntu-latest
    environment: 
      name: qa
      url: 'http://qa.test.domain'
    steps:
      - name: Deploy
        run: echo "Deploying...to...qa $GITHUB_REF"

  deploy_staging:
    name: Deploy to staging 
    needs: [deploy_qa]
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: 'http://test.domain'
    steps:
      - name: Deploy
        run: echo Deploying...to...staging

  deploy_prod:
    name: Deploy to prod
    needs: [deploy_staging]
    runs-on: ubuntu-latest
    environment: 
      name: prod
      url: 'http://test.domain'
    steps:
      - name: Deploy
        run: echo Deploying...to...staging
